const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //   //admin
  //   ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
  //   ADMIN_LOGIN_FAIL: "ADMIN_LOGIN_FAIL",s
  //   PROCESS_LOGOUT: "PROCESS_LOGOUT",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  //Admin - GET KEYS
  FETCH_KEYS_START: "FETCH_KEYS_START",
  FETCH_KEYS_SUCCESS: "FETCH_KEYS_SUCCESS",
  FETCH_KEYS_FAIL: "FETCH_KEYS_FAIL",
  //UERLOGIN_SUCCESS
  FETCH_USER_LOGIN_SUCCESS: "FETCH_USER_LOGIN_SUCCESS",
  FETCH_USER_LOGIN_FAIL: "FETCH_USER_LOGIN_FAIL ",
  //POST USER
  FETCH_CREATE_USER_START: "FETCH_CREATE_USER_START",
  FETCH_CREATE_USER_SUCCESS: "FETCH_CREATE_USER_SUCCESS",
  FETCH_CREATE_USER_FAIL: "FETCH_CREATE_USER_FAIL",
  //GET USER
  FETCH_GET_USER_START: "FETCH_GET_USER_START",
  FETCH_GET_USER_SUCCESS: "FETCH_GET_USER_SUCCESS",
  FETCH_GET_USER_FAIL: "FETCH_GET_USER_FAIL",
  //PUT USER
  FETCH_UPDATE_USER_START: "FETCH_UPDATE_USER_START ",
  FETCH_UPDATE_USER_SUCCESS: "FETCH_UPDATE_USER_SUCCESS",
  FETCH_UPDATE_USER_FAIL: "FETCH_UPDATE_USER_FAIL  ",
  //DELETE USET
  FETCH_DELETE_USER_START: " FETCH_DELETE_USER_START  ",
  FETCH_DELETE_USER_SUCCESS: " FETCH_DELETE_USER_SUCCESS ",
  FETCH_DELETE_USER_FAIL: "FETCH_DELETE_USER_FAIL     ",
  //GET DOCTOR
  FETCH_GET_TOP_DOCTOR_START: "FETCH_GET_TOP_DOCTOR_START",
  FETCH_GET_TOP_DOCTOR_SUCCESS: "FETCH_GET_TOP_DOCTOR_SUCCESS",
  FETCH_GET_TOP_DOCTOR_FAIL: "FETCH_GET_TOP_DOCTOR_FAIL",
  //GET ALL DOCTOR
  FETCH_GET_ALL_DOCTOR_START: "FETCH_GET_ALL_DOCTOR_START",
  FETCH_GET_ALL_DOCTOR_SUCCESS: "FETCH_GET_ALL_DOCTOR_SUCCESS",
  FETCH_GET_ALL_DOCTOR_FAIL: "FETCH_GET_ALL_DOCTOR_FAIL",
  // SAVE INFO DOCTOR
  FETCH_SAVE_INFO_DOCTOR_START: "FETCH_SAVE_INFO_DOCTOR_START",
  FETCH_SAVE_INFO_DOCTOR_SUCCESS: "FETCH_SAVE_INFO_DOCTOR_SUCCESS",
  FETCH_SAVE_INFO_DOCTOR_FAIL: "FETCH_SAVE_INFO_DOCTOR_FAIL",
  //GET DETAIL DOCTOR
  FETCH_GET_DETAIL_DOCTOR_SUCCESS: "FETCH_GET_DETAIL_DOCTOR_SUCCESS",
  FETCH_GET_DETAIL_DOCTOR_FAIL: "FETCH_GET_DETAIL_DOCTOR_FAIL",
  //GET ALLCODE  SCHEDULE HOURS SUCCSESS
  FETCH_ALLCODE_SCHEDULE_HOURS_SUCCESS: "FETCH_ALLCODE_SCHEDULE_HOURS_SUCCESS",
  FETCH_ALLCODE_SCHEDULE_HOURS_FAIL: "FETCH_ALLCODE_SCHEDULE_HOURS_FAIL",
  //GET REQUAIRED DOCTOR INFO
  FETCH_REQUIRED_DOCTOR_INFO_START: "FETCH_REQUIRED_DOCTOR_INFO_START",
  FETCH_REQUIRED_DOCTOR_INFO_SUCESS: "FETCH_REQUIRED_DOCTOR_INFO_SUCESS",
  FETCH_REQUIRED_DOCTOR_INFO_FAIL: "FETCH_REQUIRED_DOCTOR_INFO_FAIL",
});

export default actionTypes;
